### ISSUE TITLE
Add the possibility to display to, cc, cci

### ISSUE THREAD

**Issue by mam-ijinus** [mjstewart/fakesmtp-web#2]
Hi,
It's should be great if the mail of toRecipients , ccRecipients and bccRecipients are visible. This permits to checks these infos id needed.
thanks.

**Comment by mam-ijinus** [comment]
I see that noramlly I must see these information.  So this is a bug...

**Comment by mjstewart** [comment]
Thanks for the bug report. I noticed the toRecipients fields wasn't configured correctly and I have pushed up a new change which fixes that. All of the other email fields work by default providing these headers are in the email message that fake-smtp generates.

If you can show me the raw email for a scenario where the UI doesn't display these fields id gladly have a look but haven't come across this issue myself so I cannot replicate.

**Comment by mam-ijinus** [comment]
For the moment I use a build version of fakesmptweb, so I cannot directly update the image to test it.

for example an email :


{
      "id" : "23cea847-39c9-4d35-8822-6b7ef14e16ca",
      "subject" : "xxxx",
      "replyTo" : [ "ijitrack@ijinus.fr" ],
      "body" : {
        "content" : "xxxxxx",
        "contentType" : {
          "mediaType" : "text/html",
          "charset" : "UTF-8"
        }
      },
      "receivedDate" : null,
      "sentDate" : "2019-01-23T09:51:05",
      "description" : null,
      "toRecipients" : [ "xxx@xxx.com" ],
      "ccRecipients" : [ ],
      "bccRecipients" : [ ],
      "attachments" : [ ],
      "read" : true,
      "from" : [ "ijitrack@ijinus.fr" ],
      "_links" : {
        "self" : {
          "href" : "http://xxxx:60500/api/emails/23cea847-39c9-4d35-8822-6b7ef14e16ca"
        },
        "email" : {
          "href" : "http://xxx:60500/api/emails/23cea847-39c9-4d35-8822-6b7ef14e16ca"
        }
      }
    }

**Comment by mjstewart** [comment]
With the latest build you will be able to see all the different recipients. to, cc, bcc etc.
