### ISSUE TITLE
No body shown

### ISSUE THREAD

**Issue by aritu** [mjstewart/fakesmtp-web#6]
Hi,
I've got fakesmtp-web running on a VM (built custom image to change IP as it is explained in the documentation), and everything works fine, except that the body of the email is never shown.
I get the emails with the correct subject, from, to, etc. but "No body" in the content.

I've accessed the fakesmtp-web container, and inside /var/mail I see that all the emails have a body, so I don't know what could be wrong.

I've attached a sample email (removing sensitive data), I hope it will be helpful.

Please tell me if you need more info, and thank you for the dedication!

[mail1.eml.txt](https://github.com/mjstewart/fakesmtp-web/files/5596706/mail1.eml.txt)

**Comment by mjstewart** [comment]
Hello, thanks for the issue report and the example email (awesome of you).

I suspected this would happen at some point as I didn't spend much time on the email parsing logic.

I've made a few changes, specifically now using the apache commons mail parser.

Please try out the new version `image: mjstewart/fakesmtp-web:1.3`. (I checked it with your example email and the body now shows up).
